"""empty message

Revision ID: c7eecb058963
Revises: 6e3043584fa1
Create Date: 2021-03-14 13:06:35.182901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7eecb058963'
down_revision = '6e3043584fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animes', sa.Column('vault_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'animes', 'vaults', ['vault_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'animes', type_='foreignkey')
    op.drop_column('animes', 'vault_id')
    # ### end Alembic commands ###
